<a href="https://colab.research.google.com/github/sereenajoshy/AI-ML-Intership/blob/main/DAY_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

In [17]:
df=pd.read_csv("/content/Zudio_sales_data.csv")

In [18]:
df

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
0,Zudio,India,Karnataka,Jalna,Women,Dresses,30,411084,Owned,2022-06-04,...,Alarm,88240,2024-11-06,November,233084,Michele Ochoa,354,1958,5,3916.0
1,Zudio,India,Gujarat,Patna,Kids,Skirts,48,404562,Owned,2020-12-19,...,Alarm,78145,2024-06-17,June,926472,Daniel Jimenez,741,2078,1,831.2
2,Zudio,India,Uttar Pradesh,Kolkata,Men,Hoodies,97,437773,Rented,2023-09-04,...,CCTV,33363,2024-08-17,August,853255,Steven Davis,607,1445,2,1156.0
3,Zudio,India,West Bengal,Kolkata,Women,Dresses,93,431725,Owned,2024-04-11,...,CCTV,46682,2024-03-27,March,106146,Derek Orozco,991,2469,6,5925.6
4,Zudio,India,West Bengal,Guwahati,Men,Dresses,51,415370,Owned,2022-05-29,...,"CCTV, Alarm",58242,2024-04-08,April,264070,Victor Arnold,479,1105,6,2652.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7894,Zudio,India,Uttar Pradesh,Chandigarh,Kids,Jeans,32,431437,Owned,2024-04-24,...,"CCTV, Alarm",39056,2024-09-27,September,591993,Tracey Andrews,262,2838,1,1135.2
7895,Zudio,India,Uttar Pradesh,Aurangabad,Kids,Jackets,52,424643,Owned,2024-02-03,...,Alarm,85486,2024-03-16,March,822244,Linda Wallace,537,1814,2,1451.2
7896,Zudio,India,Tamil Nadu,Pune,Kids,T-shirts,81,412057,Owned,2021-04-11,...,"CCTV, Alarm",78200,2024-12-02,December,268376,Brandon Baker,457,1961,1,784.4
7897,Zudio,India,Delhi,Madurai,Men,Shoes,58,405203,Rented,2022-06-17,...,CCTV,19883,2024-07-29,July,766283,John Lewis,608,1017,8,3254.4
7898,Zudio,India,Gujarat,Bengaluru,Women,Shirts,20,429823,Owned,2023-02-08,...,"CCTV, Alarm",91451,2024-04-08,April,541226,Nicholas Salazar,583,2773,5,5546.0

In [19]:
df.head()

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
0,Zudio,India,Karnataka,Jalna,Women,Dresses,30,411084,Owned,2022-06-04,...,Alarm,88240,2024-11-06,November,233084,Michele Ochoa,354,1958,5,3916.0
1,Zudio,India,Gujarat,Patna,Kids,Skirts,48,404562,Owned,2020-12-19,...,Alarm,78145,2024-06-17,June,926472,Daniel Jimenez,741,2078,1,831.2
2,Zudio,India,Uttar Pradesh,Kolkata,Men,Hoodies,97,437773,Rented,2023-09-04,...,CCTV,33363,2024-08-17,August,853255,Steven Davis,607,1445,2,1156.0
3,Zudio,India,West Bengal,Kolkata,Women,Dresses,93,431725,Owned,2024-04-11,...,CCTV,46682,2024-03-27,March,106146,Derek Orozco,991,2469,6,5925.6
4,Zudio,India,West Bengal,Guwahati,Men,Dresses,51,415370,Owned,2022-05-29,...,"CCTV, Alarm",58242,2024-04-08,April,264070,Victor Arnold,479,1105,6,2652.0

In [20]:
df.tail()

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
7894,Zudio,India,Uttar Pradesh,Chandigarh,Kids,Jeans,32,431437,Owned,2024-04-24,...,"CCTV, Alarm",39056,2024-09-27,September,591993,Tracey Andrews,262,2838,1,1135.2
7895,Zudio,India,Uttar Pradesh,Aurangabad,Kids,Jackets,52,424643,Owned,2024-02-03,...,Alarm,85486,2024-03-16,March,822244,Linda Wallace,537,1814,2,1451.2
7896,Zudio,India,Tamil Nadu,Pune,Kids,T-shirts,81,412057,Owned,2021-04-11,...,"CCTV, Alarm",78200,2024-12-02,December,268376,Brandon Baker,457,1961,1,784.4
7897,Zudio,India,Delhi,Madurai,Men,Shoes,58,405203,Rented,2022-06-17,...,CCTV,19883,2024-07-29,July,766283,John Lewis,608,1017,8,3254.4
7898,Zudio,India,Gujarat,Bengaluru,Women,Shirts,20,429823,Owned,2023-02-08,...,"CCTV, Alarm",91451,2024-04-08,April,541226,Nicholas Salazar,583,2773,5,5546.0

In [21]:
df.tail(10)

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
7889,Zudio,India,Uttar Pradesh,Madurai,Kids,T-shirts,82,429075,Rented,2023-03-08,...,Alarm,50154,2024-05-02,May,158047,Timothy Atkinson,901,1340,7,3752.0
7890,Zudio,India,Maharashtra,Indore,Kids,Shirts,12,402636,Rented,2023-02-12,...,Alarm,65868,2024-05-28,May,193390,Marco Pratt,810,1626,4,2601.6
7891,Zudio,India,Tamil Nadu,Kochi,Men,Dresses,83,431699,Owned,2020-04-25,...,"CCTV, Alarm",24791,2024-03-25,March,465109,Justin Rivera,393,2653,6,6367.2
7892,Zudio,India,Uttar Pradesh,Vadodara,Women,Sweaters,39,403376,Owned,2022-09-07,...,NaN,75845,2024-11-14,November,356017,Justin Diaz,746,1357,6,3256.8
7893,Zudio,India,Rajasthan,Hyderabad,Women,Jackets,96,415258,Rented,2020-04-23,...,"CCTV, Alarm",33083,2024-01-06,January,801703,Bryan Walker,242,2169,6,5205.6
7894,Zudio,India,Uttar Pradesh,Chandigarh,Kids,Jeans,32,431437,Owned,2024-04-24,...,"CCTV, Alarm",39056,2024-09-27,September,591993,Tracey Andrews,262,2838,1,1135.2
7895,Zudio,India,Uttar Pradesh,Aurangabad,Kids,Jackets,52,424643,Owned,2024-02-03,...,Alarm,85486,2024-03-16,March,822244,Linda Wallace,537,1814,2,1451.2
7896,Zudio,India,Tamil Nadu,Pune,Kids,T-shirts,81,412057,Owned,2021-04-11,...,"CCTV, Alarm",78200,2024-12-02,December,268376,Brandon Baker,457,1961,1,784.4
7897,Zudio,India,Delhi,Madurai,Men,Shoes,58,405203,Rented,2022-06-17,...,CCTV,19883,2024-07-29,July,766283,John Lewis,608,1017,8,3254.4
7898,Zudio,India,Gujarat,Bengaluru,Women,Shirts,20,429823,Owned,2023-02-08,...,"CCTV, Alarm",91451,2024-04-08,April,541226,Nicholas Salazar,583,2773,5,5546.0

In [22]:
df.head(3)

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
0,Zudio,India,Karnataka,Jalna,Women,Dresses,30,411084,Owned,2022-06-04,...,Alarm,88240,2024-11-06,November,233084,Michele Ochoa,354,1958,5,3916.0
1,Zudio,India,Gujarat,Patna,Kids,Skirts,48,404562,Owned,2020-12-19,...,Alarm,78145,2024-06-17,June,926472,Daniel Jimenez,741,2078,1,831.2
2,Zudio,India,Uttar Pradesh,Kolkata,Men,Hoodies,97,437773,Rented,2023-09-04,...,CCTV,33363,2024-08-17,August,853255,Steven Davis,607,1445,2,1156.0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7899 entries, 0 to 7898
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      7899 non-null   object
 1   Country                    7899 non-null   object
 2   State                      7899 non-null   object
 3   City                       7899 non-null   object
 4   Category                   7899 non-null   object
 5   Clothing Type              7899 non-null   object
 6   Store Number               7899 non-null   int64
 7   Postal Code                7899 non-null   int64
 8   Store Type                 7899 non-null   object
 9   Store Open Date            7899 non-null   object
 10  Selling Area Size (sq ft)  7899 non-null   int64
 11  Store Manager              7899 non-null   object
 12  Manager ID                 7899 non-null   object
 13  Store Address              7899 non-null   object
 14  Contact Information        7899 non-null   object
 15  Operating Hours            7899 non-null   object
 16  Staff Count                7899 non-null   int64
 17  Parking Availability       7899 non-null   object
 18  Security Features          5861 non-null   object
 19  Order ID                   7899 non-null   int64
 20  Order Date                 7899 non-null   object
 21  Month                      7899 non-null   object
 22  Customer ID                7899 non-null   int64
 23  Customer Name              7899 non-null   object
 24  Product ID                 7899 non-null   int64
 25  Price                      7899 non-null   int64
 26  Quantity                   7899 non-null   int64
 27  Sales Profit               7899 non-null   float64
dtypes: float64(1), int64(9), object(18)
memory usage: 1.7+ MB

In [24]:
df.shape

(7899, 28)

In [25]:
df.dtypes

Store                         object
Country                       object
State                         object
City                          object
Category                      object
Clothing Type                 object
Store Number                   int64
Postal Code                    int64
Store Type                    object
Store Open Date               object
Selling Area Size (sq ft)      int64
Store Manager                 object
Manager ID                    object
Store Address                 object
Contact Information           object
Operating Hours               object
Staff Count                    int64
Parking Availability          object
Security Features             object
Order ID                       int64
Order Date                    object
Month                         object
Customer ID                    int64
Customer Name                 object
Product ID                     int64
Price                          int64
Quantity                       int64
Sales Profit                 float64
dtype: object

In [26]:
df.describe()

,Store Number,Postal Code,Selling Area Size (sq ft),Staff Count,Order ID,Customer ID,Product ID,Price,Quantity,Sales Profit
count,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000
mean,50.666034,419982.374984,1112.077478,11.504747,54920.719965,549440.714521,602.069376,1761.113432,4.519433,3170.671376
std,29.095274,11695.237817,193.239371,5.194722,25894.206850,262418.912565,232.066189,716.269447,2.292373,2141.249886
min,1.000000,400006.000000,800.000000,3.000000,10008.000000,100153.000000,204.000000,499.000000,1.000000,200.400000
25%,25.000000,409841.000000,950.000000,7.000000,33192.000000,318516.500000,398.000000,1136.000000,3.000000,1411.200000
50%,51.000000,419988.000000,1100.000000,12.000000,54873.000000,546012.000000,602.000000,1782.000000,5.000000,2681.600000
75%,76.000000,430258.000000,1300.000000,16.000000,77285.000000,780304.000000,803.500000,2373.000000,7.000000,4570.400000
max,100.000000,439985.000000,1400.000000,20.000000,99999.000000,999858.000000,999.000000,2999.000000,8.000000,9596.800000

In [27]:
df[['Postal Code','Product ID']]

      Postal Code  Product ID
0          411084         354
1          404562         741
2          437773         607
3          431725         991
4          415370         479
...           ...         ...
7894       431437         262
7895       424643         537
7896       412057         457
7897       405203         608
7898       429823         583

[7899 rows x 2 columns]

In [28]:
df.isnull()

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7894,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7895,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7896,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7897,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7898,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [29]:
df.isnull().sum()

Store                           0
Country                         0
State                           0
City                            0
Category                        0
Clothing Type                   0
Store Number                    0
Postal Code                     0
Store Type                      0
Store Open Date                 0
Selling Area Size (sq ft)       0
Store Manager                   0
Manager ID                      0
Store Address                   0
Contact Information             0
Operating Hours                 0
Staff Count                     0
Parking Availability            0
Security Features            2038
Order ID                        0
Order Date                      0
Month                           0
Customer ID                     0
Customer Name                   0
Product ID                      0
Price                           0
Quantity                        0
Sales Profit                    0
dtype: int64